# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9e0df8cd128dd2aa71dbd5871fdf90d4"
name = "qr-app"
handle = "qr-app-125"
application_url = "https://blessed-built-screen-demographic.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-e92d3db1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://blessed-built-screen-demographic.trycloudflare.com/auth/callback",
  "https://blessed-built-screen-demographic.trycloudflare.com/auth/shopify/callback",
  "https://blessed-built-screen-demographic.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
